### ISSUE TITLE
Generate missing input files for Rqtl2

### ISSUE THREAD

**Issue by mgalland** [Mtusti05/qtl-analysis#3]
Phenotype file (pheromones)
Covariate file (sex)

**Comment by mgalland** [comment]
@Mtusti05 Make sure you integrate both male and female lines.

**Comment by Arlettt** [comment]
I don't fully understand the covariate file for our dataset, but I tried something. Can you have a look?

**Comment by mgalland** [comment]
The `phenocovar` looks good to me. This file would needs to be listed in the YAML control file for Rqtl2 to take it into account. But it should works! And hopefully reduce your linkage group number to a more reasonable number 😄

**Comment by Arlettt** [comment]
Well, I lost all hope in this data set :')
The phenocovar file has been added to the yaml file.

**Comment by mgalland** [comment]
You're becoming a real-life scientist that's harsh! All datasets are not like "tutorial datasets" unfortunately 🤕 
On which branch have you done the YAML file modification? I don't see it.

**Comment by Arlettt** [comment]
Oh sorry I did it on the master branch
